project:
  type: book
  output-dir: docs

book:
  title: "DS2023 Catapult Group 2 Final Project"
  subtitle: "Preventing Fatigue and Injury in Collegiate Basketball"
  author: "Alka Link, Grace Pitts, Kieran Perdue, Michael Carlson"
  favicon: logo.png
  description: "A demo book for DS2023"
  keyword: data science, communicating, storytelling, data visualization, data design
  #url:
  #sidebar: 
   # logo: logo.png
    #search: true
    #repo-url: https://github.com/mrcarlson3/DS2023Proj
    #repo-branch: main
    #image: logo.png

  chapters:
    - index.qmd
    - datalearning.qmd
    - eda.qmd
    - dataviz.qmd
    - datadictionary.qmd



format:
  html:
    theme:
      light: superhero
    code-fold: false
    backgroundcolor: '#FFFFFF'



